# Generated by Django 5.0.2 on 2024-02-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientName', models.CharField(max_length=255)),
                ('clientIP', models.GenericIPAddressField()),
                ('clientPort', models.IntegerField()),
                ('clientUsername', models.CharField(max_length=255)),
                ('clientPassword', models.CharField(max_length=255)),
                ('clientLab', models.CharField(max_length=255)),
                ('traffic_profile', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
