# Generated by Django 5.0.2 on 2024-03-18 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_bssid_client_channel_client_channel_band_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='noise_measurement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
