# Generated by Django 5.0.2 on 2024-03-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_noise_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='interface',
            field=models.CharField(default='en1', max_length=255),
        ),
    ]
