# Generated by Django 5.0.2 on 2024-03-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_interface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='interface',
            field=models.CharField(max_length=255),
        ),
    ]
