# Generated by Django 5.0.2 on 2024-03-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_client_interface'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='channel_band',
            new_name='channelband',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='channel_width',
            new_name='channelwidth',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='noise_measurement',
            new_name='noisemeasurement',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='ssid',
            new_name='ssidname',
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('clientIP', 'clientPort')},
        ),
    ]
