# Generated by Django 5.0.4 on 2024-04-08 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_remove_client_client_name_client_hostname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='phyrate',
        ),
    ]
